### ISSUE TITLE
Pycket version

### ISSUE THREAD

**Issue by bennn** [btlachance/pycket-docker#1]
What are the Pycket & pypy versions that get checked out in the Dockerfile? Are they OOPSLA or ICFP?

fwiw I liked the earlier version that listed both

Also, yesterday I was happy to learn that pycket & pypy build on their master branches, without checking out any specific commits

**Comment by btlachance** [comment]
[These](https://github.com/btlachance/pycket-docker/blob/0a07dbd24ea9e19634b4d798a8208705edd5dfc5/Dockerfile) versions are from OOPSLA17.

And I also liked the earlier Dockerfile that listed both; completely forgot it was a thing :)

Sounds like there should be a couple Dockerfile's-- e.g. one for Pycket+PyPy master, one for the OOPSLA revisions.

**Comment by bennn** [comment]
Ok, I opened a pull request to document the current state of things

**Comment by btlachance** [comment]
I can't think of any reasons for you to not have the collaborator bit, so... want to be a collaborator?

**Comment by bennn** [comment]
Sure, thank you!

(I don't plan on using it --- but we'll see)
